listener 1883
allow_anonymous false

listener 8883
certfile /mosquitto/config/certs/broker.crt
keyfile /mosquitto/config/certs/broker.key
cafile /mosquitto/config/certs/ca.crt
tls_version tlsv1.2

password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl.acl

# Persistencia: los mensajes retenidos (umbrales) sobreviven reinicios del broker
persistence true
persistence_location /mosquitto/data/
